<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FalimyCalc.Data\FalimyCalc.Data.csproj" />
    <ProjectReference Include="..\FalimyCalc.Shared\FalimyCalc.Shared.csproj" />
  </ItemGroup>

</Project>
